# Generated by Django 3.1.3 on 2020-11-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.activation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
    ]
