# Generated by Django 3.1.4 on 2021-01-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210111_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
