# Generated by Django 3.1.4 on 2021-01-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210112_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimesheet',
            name='campus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.campus'),
            preserve_default=False,
        ),
    ]
